general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # ensure display turns on after wake
}

# Listener to turn off display after 1 minute
listener {
    timeout = 60                                # 1 minute
    on-timeout = hyprctl dispatch dpms off      # turn off monitor
    on-resume = hyprctl dispatch dpms on       # turn on monitor on activity
}

# Listener to lock screen after 3 minutes
listener {
    timeout = 180                               # 3 minutes
    on-timeout = hyprlock                       # lock screen
    on-resume = hyprctl reload
}

# Listener to suspend after 15 minutes
listener {
    timeout = 900                               # 15 minutes
    on-timeout = systemctl suspend              # suspend system
}