#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = waybar
exec-once = hypridle
exec-once = swaync # แถบด้านบน + ระบบล็อกจอ + ระบบแจ้งเตือน
exec-once = gammastep -l 13.7569:100.501 -O 4000 # blue light
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
