# workaround for jetbrains IDEs dropdowns/popups cause flickering
windowrule = no_initial_focus true,match:class ^(.*jetbrains.*)$,match:title ^(win[0-9]+)$
windowrule = no_initial_focus true,match:class ^(clipstudiopaint\.exe)$,match:title ^(CLIP STUDIO PAINT.*)$

# Blur -----------------------------------------------------

layerrule = blur true, match:namespace waybar
layerrule = blur true, match:namespace rofi
layerrule = ignore_alpha 0, match:namespace rofi
layerrule = blur true, match:namespace notifications
layerrule = ignore_alpha 0, match:namespace notifications
layerrule = blur true,match:namespace swaync-notification-window
layerrule = ignore_alpha 0, match:namespace swaync-notification-window
layerrule = blur true,match:namespace swaync-control-center
layerrule = ignore_alpha 0, match:namespace swaync-control-center
layerrule = blur true,match:namespace logout_dialog
